# see http://docs.travis-ci.com/user/languages/java/
language: java
jdk:
  - oraclejdk8

# see http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# see http://docs.travis-ci.com/user/caching/#Arbitrary-directories
cache:
  directories:
  - $HOME/.m2

after_success:
- mvn clean test jacoco:report coveralls:report

addons:
  coverity_scan:
    project:
      name: "sebhoss/generic-types"
      description: "Build submitted via Travis CI"
    notification_email: mail@shoss.de
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: master

# see http://docs.travis-ci.com/user/notifications/
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/edb8925a63dc836c317c
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
